name: Build

on:
  push:
    branches: ['master']
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: ['master']
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  PROJECT_PATH: 'src/Jailbreak/Jailbreak.csproj'
  PROJECT_NAME: 'CS2-Jailbreak'
  OUTPUT_PATH: './CS2-Jailbreak'
  SOLUTION_PATH: 'CS2-Jailbreak.sln'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release -o ${{ env.OUTPUT_PATH }} -r linux-x64 --self-contained false

  publish:
    if: github.event_name == 'push'
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release -o ${{ env.OUTPUT_PATH }} -r linux-x64 --self-contained false

      - name: Clean files
        run: |
          rm -f \
            ${{ env.OUTPUT_PATH }}/CounterStrikeSharp.API.dll \
            ${{ env.OUTPUT_PATH }}/McMaster.NETCore.Plugins.dll \
            ${{ env.OUTPUT_PATH }}/Microsoft.DotNet.PlatformAbstractions.dll \
            ${{ env.OUTPUT_PATH }}/Microsoft.Extensions.DependencyModel.dll \

      - name: Zip
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: '${{ env.PROJECT_NAME }}.zip'
          path: ${{ env.OUTPUT_PATH }}

      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: '${{ env.PROJECT_NAME }}.zip'
          name: 'Build ${{ env.BUILD_NUMBER }}'
          tag: 'build-${{ env.BUILD_NUMBER }}'
          body: |
            Place the plugin in game/csgo/addons/counterstrikesharp/plugins/CS2-Jailbreak
